### PR TITLE
Add a notebook to display a range of adjacent CSDS

### PR DESCRIPTION
**Pull request by ljgray**
Add an extra notebook to display a consecutive range of delay spectra

### CODE REVIEW

**Review by rikvl — COMMENTED** [review]
This is good as far as I can tell. I found a few tiny things to fix.

Also, could you maybe also add the label to the color axis in the list view, so in `plotDS`?

**Comment by ljgray** [comment]
> This is good as far as I can tell. I found a few tiny things to fix.
> 
> Also, could you maybe also add the label to the color axis in the list view, so in `plotDS`?

I think all items should be addressed now

**Review by rikvl — APPROVED** [review]
Thanks Liam!

**Comment by ljgray** [comment]
@jrs65 I made a couple of additions to the run script
- Adding the 14-day notebook
- Setting a separate output directory
- Removing the temporary files

**Pull request merged**
